import express from 'express';
import { getCarAndSlotCount } from './routes/getCarAndSlotCount.js';
import { getRemovedCarsData } from './routes/getRemovedCarsData.js';
import { getCarSlotByRegNumber } from './routes/getCarSlotByRegNumber.js';
import { getCarSlotsByColor } from './routes/getCarSlotsByColor.js';
import { getParkedCarsData } from './routes/getParkedCarsData.js';
import { getSameColorCarsData } from './routes/getSameColorCarsData.js';
import { renderHomePage } from './routes/renderHomePage.js';
import { renderLoginPage } from './routes/renderLoginPage.js';
import { renderRegisterPage } from './routes/renderRegisterPage.js';
import { addUser } from './routes/registerUser.js';
import { loginUser } from './routes/loginUser.js';
import { addCar } from './routes/parkedYourCar.js';
import { removeCar } from './routes/removeCar.js';
import { clearRemovedCarsData } from './routes/clearRemovedCarsData.js';
const router = express.Router();
router.use(getCarAndSlotCount);
router.use(addUser);
router.use(addCar);
router.use(removeCar);
router.use(clearRemovedCarsData);
router.use(loginUser);
router.use(renderHomePage);
router.use(renderRegisterPage);
router.use(renderLoginPage);
router.use(getParkedCarsData);
router.use(getSameColorCarsData);
router.use(getCarSlotByRegNumber);
router.use(getCarSlotsByColor);
router.use(getRemovedCarsData);
export { router };
